// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DiscoveryRequest {
    #[prost(string, tag="1")]
    pub node_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub cluster: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub version: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub nonce: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="5")]
    pub subscriptions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(enumeration="DiscoveryResultStatus", tag="6")]
    pub result_status: i32,
    #[prost(string, tag="7")]
    pub error_detail: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="8")]
    pub supported_features: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DiscoveryResponse {
    #[prost(string, tag="1")]
    pub version: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub nonce: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub snapshot: ::core::option::Option<ConfigSnapshot>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StatusReport {
    #[prost(string, tag="1")]
    pub node_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub version: ::prost::alloc::string::String,
    #[prost(bool, tag="3")]
    pub ready: bool,
    #[prost(string, tag="4")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, optional, tag="5")]
    pub observed_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StatusAck {
    #[prost(bool, tag="1")]
    pub accepted: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConfigSnapshot {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub generated_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, repeated, tag="3")]
    pub listeners: ::prost::alloc::vec::Vec<Listener>,
    #[prost(message, repeated, tag="4")]
    pub http_routes: ::prost::alloc::vec::Vec<HttpRoute>,
    #[prost(message, repeated, tag="5")]
    pub grpc_routes: ::prost::alloc::vec::Vec<GrpcRoute>,
    #[prost(message, repeated, tag="6")]
    pub stream_routes: ::prost::alloc::vec::Vec<StreamRoute>,
    #[prost(message, repeated, tag="7")]
    pub backends: ::prost::alloc::vec::Vec<BackendCluster>,
    #[prost(message, repeated, tag="8")]
    pub secrets: ::prost::alloc::vec::Vec<SecretMaterial>,
    #[prost(message, optional, tag="9")]
    pub extensions: ::core::option::Option<::prost_types::Struct>,
    #[prost(string, repeated, tag="10")]
    pub required_features: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag="11")]
    pub compatibility_profile: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Listener {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub address: ::prost::alloc::string::String,
    #[prost(uint32, tag="3")]
    pub port: u32,
    #[prost(enumeration="ListenerProtocol", tag="4")]
    pub protocol: i32,
    #[prost(string, repeated, tag="5")]
    pub hostnames: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag="6")]
    pub attached_routes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag="7")]
    pub tls: ::core::option::Option<TlsConfig>,
    #[prost(map="string, string", tag="8")]
    pub metadata: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(message, optional, tag="9")]
    pub backend_tls: ::core::option::Option<BackendTlsConfig>,
    #[prost(string, repeated, tag="10")]
    pub addresses: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TlsConfig {
    #[prost(bool, tag="1")]
    pub enabled: bool,
    #[prost(bool, tag="2")]
    pub passthrough: bool,
    #[prost(string, repeated, tag="3")]
    pub secret_refs: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag="4")]
    pub sni_hosts: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag="5")]
    pub min_version: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub max_version: ::prost::alloc::string::String,
    #[prost(message, optional, tag="7")]
    pub frontend_validation: ::core::option::Option<FrontendValidation>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FrontendValidation {
    #[prost(string, repeated, tag="1")]
    pub ca_pems: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag="2")]
    pub mode: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BackendTlsConfig {
    #[prost(string, tag="1")]
    pub client_certificate_ref: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BackendTlsValidation {
    #[prost(string, tag="1")]
    pub hostname: ::prost::alloc::string::String,
    #[prost(bool, tag="2")]
    pub use_system_ca_certificates: bool,
    #[prost(string, repeated, tag="3")]
    pub ca_pems: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag="4")]
    pub subject_alt_names: ::prost::alloc::vec::Vec<BackendTlsSubjectAltName>,
    #[prost(string, tag="5")]
    pub min_version: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub max_version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BackendTlsSubjectAltName {
    #[prost(enumeration="BackendTlsSubjectAltNameType", tag="1")]
    pub r#type: i32,
    #[prost(string, tag="2")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HttpRoute {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub namespace: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="3")]
    pub hostnames: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag="4")]
    pub parent_refs: ::prost::alloc::vec::Vec<ParentRef>,
    #[prost(message, repeated, tag="5")]
    pub rules: ::prost::alloc::vec::Vec<HttpRule>,
    #[prost(map="string, string", tag="6")]
    pub labels: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(map="string, string", tag="7")]
    pub annotations: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HttpRule {
    #[prost(message, repeated, tag="1")]
    pub matches: ::prost::alloc::vec::Vec<HttpMatch>,
    #[prost(message, repeated, tag="2")]
    pub filters: ::prost::alloc::vec::Vec<Filter>,
    #[prost(message, repeated, tag="3")]
    pub backend_refs: ::prost::alloc::vec::Vec<BackendRef>,
    #[prost(message, optional, tag="4")]
    pub timeouts: ::core::option::Option<HttpRouteTimeouts>,
    #[prost(message, optional, tag="5")]
    pub retry: ::core::option::Option<HttpRouteRetry>,
    #[prost(message, optional, tag="6")]
    pub session_persistence: ::core::option::Option<SessionPersistence>,
    #[prost(string, tag="7")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HttpMatch {
    #[prost(string, tag="1")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub path_type: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub method: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="4")]
    pub headers: ::prost::alloc::vec::Vec<HeaderMatch>,
    #[prost(message, repeated, tag="5")]
    pub query_params: ::prost::alloc::vec::Vec<QueryMatch>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HttpRouteTimeouts {
    #[prost(message, optional, tag="1")]
    pub request: ::core::option::Option<::prost_types::Duration>,
    #[prost(message, optional, tag="2")]
    pub backend_request: ::core::option::Option<::prost_types::Duration>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HttpRouteRetry {
    #[prost(uint32, repeated, tag="1")]
    pub codes: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint32, tag="2")]
    pub attempts: u32,
    #[prost(message, optional, tag="3")]
    pub backoff: ::core::option::Option<::prost_types::Duration>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CookieConfig {
    #[prost(enumeration="CookieLifetimeType", tag="1")]
    pub lifetime_type: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SessionPersistence {
    #[prost(string, tag="1")]
    pub session_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub absolute_timeout: ::core::option::Option<::prost_types::Duration>,
    #[prost(message, optional, tag="3")]
    pub idle_timeout: ::core::option::Option<::prost_types::Duration>,
    #[prost(enumeration="SessionPersistenceType", tag="4")]
    pub r#type: i32,
    #[prost(message, optional, tag="5")]
    pub cookie: ::core::option::Option<CookieConfig>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConsistentHashPolicy {
    #[prost(enumeration="ConsistentHashKeyType", tag="1")]
    pub key_type: i32,
    #[prost(string, tag="2")]
    pub header_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoadBalancingPolicy {
    #[prost(enumeration="LoadBalancingPolicyType", tag="1")]
    pub r#type: i32,
    #[prost(message, optional, tag="2")]
    pub consistent_hash: ::core::option::Option<ConsistentHashPolicy>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GrpcRoute {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub namespace: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="3")]
    pub hostnames: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag="4")]
    pub parent_refs: ::prost::alloc::vec::Vec<ParentRef>,
    #[prost(message, repeated, tag="5")]
    pub rules: ::prost::alloc::vec::Vec<GrpcRule>,
    #[prost(map="string, string", tag="6")]
    pub labels: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(map="string, string", tag="7")]
    pub annotations: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GrpcRule {
    #[prost(message, repeated, tag="1")]
    pub matches: ::prost::alloc::vec::Vec<GrpcMatch>,
    #[prost(message, repeated, tag="2")]
    pub filters: ::prost::alloc::vec::Vec<Filter>,
    #[prost(message, repeated, tag="3")]
    pub backend_refs: ::prost::alloc::vec::Vec<BackendRef>,
    #[prost(message, optional, tag="4")]
    pub session_persistence: ::core::option::Option<SessionPersistence>,
    #[prost(string, tag="5")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GrpcMatch {
    #[prost(string, tag="1")]
    pub service: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub method: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="3")]
    pub headers: ::prost::alloc::vec::Vec<HeaderMatch>,
    #[prost(string, tag="4")]
    pub match_type: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamRoute {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub namespace: ::prost::alloc::string::String,
    #[prost(enumeration="RouteKind", tag="3")]
    pub kind: i32,
    #[prost(message, repeated, tag="4")]
    pub parent_refs: ::prost::alloc::vec::Vec<ParentRef>,
    #[prost(message, repeated, tag="5")]
    pub rules: ::prost::alloc::vec::Vec<StreamRule>,
    #[prost(map="string, string", tag="6")]
    pub labels: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(map="string, string", tag="7")]
    pub annotations: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamRule {
    #[prost(message, repeated, tag="1")]
    pub matches: ::prost::alloc::vec::Vec<StreamMatch>,
    #[prost(message, repeated, tag="2")]
    pub backend_refs: ::prost::alloc::vec::Vec<BackendRef>,
    #[prost(string, tag="3")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StreamMatch {
    #[prost(uint32, tag="1")]
    pub port: u32,
    #[prost(string, tag="2")]
    pub sni_hostname: ::prost::alloc::string::String,
    #[prost(enumeration="TlsRouteMode", tag="3")]
    pub mode: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ParentRef {
    #[prost(string, tag="1")]
    pub group: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub kind: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub namespace: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub section_name: ::prost::alloc::string::String,
    #[prost(uint32, tag="6")]
    pub port: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BackendRef {
    #[prost(string, tag="1")]
    pub group: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub kind: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub namespace: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub name: ::prost::alloc::string::String,
    #[prost(uint32, tag="5")]
    pub port: u32,
    #[prost(uint32, tag="6")]
    pub weight: u32,
    #[prost(map="string, string", tag="7")]
    pub metadata: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(message, repeated, tag="8")]
    pub filters: ::prost::alloc::vec::Vec<Filter>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BackendCluster {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub namespace: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub protocol: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="4")]
    pub endpoints: ::prost::alloc::vec::Vec<BackendEndpoint>,
    #[prost(message, optional, tag="5")]
    pub connect_timeout: ::core::option::Option<::prost_types::Duration>,
    #[prost(message, optional, tag="6")]
    pub request_timeout: ::core::option::Option<::prost_types::Duration>,
    #[prost(map="string, string", tag="7")]
    pub metadata: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(message, optional, tag="8")]
    pub tls_validation: ::core::option::Option<BackendTlsValidation>,
    #[prost(message, optional, tag="9")]
    pub session_persistence: ::core::option::Option<SessionPersistence>,
    #[prost(message, optional, tag="10")]
    pub load_balancing: ::core::option::Option<LoadBalancingPolicy>,
    #[prost(message, optional, tag="11")]
    pub ai_service: ::core::option::Option<AiServiceConfig>,
    #[prost(message, optional, tag="12")]
    pub token_policy: ::core::option::Option<TokenPolicyConfig>,
    #[prost(message, optional, tag="13")]
    pub wasm_plugin: ::core::option::Option<WasmPluginConfig>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BackendEndpoint {
    #[prost(string, tag="1")]
    pub address: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub port: u32,
    #[prost(bool, tag="3")]
    pub healthy: bool,
    #[prost(string, tag="4")]
    pub zone: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HeaderMatch {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub value: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub match_type: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryMatch {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub value: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub match_type: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Filter {
    #[prost(string, tag="1")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub config: ::core::option::Option<::prost_types::Struct>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SecretMaterial {
    #[prost(string, tag="1")]
    pub namespace: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub cert_pem: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub key_pem: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AiServiceConfig {
    #[prost(string, tag="1")]
    pub provider: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub format: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub model: ::prost::alloc::string::String,
    #[prost(message, optional, tag="4")]
    pub auth: ::core::option::Option<AiServiceAuthConfig>,
    #[prost(message, optional, tag="5")]
    pub timeout: ::core::option::Option<::prost_types::Duration>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AiServiceAuthConfig {
    #[prost(string, tag="1")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub secret_ref: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub header: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenPolicyConfig {
    #[prost(uint64, tag="1")]
    pub tokens_per_minute: u64,
    #[prost(uint64, tag="2")]
    pub tokens_per_hour: u64,
    #[prost(uint64, tag="3")]
    pub requests_per_minute: u64,
    #[prost(string, tag="4")]
    pub scope: ::prost::alloc::string::String,
    #[prost(double, tag="5")]
    pub burst: f64,
    #[prost(string, tag="6")]
    pub on_limit: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WasmPluginConfig {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub namespace: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="3")]
    pub wasm_bytes: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="4")]
    pub sha256: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="5")]
    pub hooks: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag="6")]
    pub config_json: ::prost::alloc::string::String,
    #[prost(message, optional, tag="7")]
    pub sandbox: ::core::option::Option<WasmSandboxConfig>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WasmSandboxConfig {
    #[prost(uint64, tag="1")]
    pub max_memory_bytes: u64,
    #[prost(uint64, tag="2")]
    pub max_execution_time_ms: u64,
    #[prost(bool, tag="3")]
    pub allow_network: bool,
    #[prost(bool, tag="4")]
    pub allow_file_system: bool,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DiscoveryResultStatus {
    Unspecified = 0,
    Ack = 1,
    Nack = 2,
}
impl DiscoveryResultStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "DISCOVERY_RESULT_STATUS_UNSPECIFIED",
            Self::Ack => "DISCOVERY_RESULT_STATUS_ACK",
            Self::Nack => "DISCOVERY_RESULT_STATUS_NACK",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DISCOVERY_RESULT_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "DISCOVERY_RESULT_STATUS_ACK" => Some(Self::Ack),
            "DISCOVERY_RESULT_STATUS_NACK" => Some(Self::Nack),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ListenerProtocol {
    Unspecified = 0,
    Http = 1,
    Https = 2,
    Grpc = 3,
    Http3 = 4,
    Tcp = 5,
    Udp = 6,
    TlsPassthrough = 7,
    Tls = 8,
}
impl ListenerProtocol {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "LISTENER_PROTOCOL_UNSPECIFIED",
            Self::Http => "LISTENER_PROTOCOL_HTTP",
            Self::Https => "LISTENER_PROTOCOL_HTTPS",
            Self::Grpc => "LISTENER_PROTOCOL_GRPC",
            Self::Http3 => "LISTENER_PROTOCOL_HTTP3",
            Self::Tcp => "LISTENER_PROTOCOL_TCP",
            Self::Udp => "LISTENER_PROTOCOL_UDP",
            Self::TlsPassthrough => "LISTENER_PROTOCOL_TLS_PASSTHROUGH",
            Self::Tls => "LISTENER_PROTOCOL_TLS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LISTENER_PROTOCOL_UNSPECIFIED" => Some(Self::Unspecified),
            "LISTENER_PROTOCOL_HTTP" => Some(Self::Http),
            "LISTENER_PROTOCOL_HTTPS" => Some(Self::Https),
            "LISTENER_PROTOCOL_GRPC" => Some(Self::Grpc),
            "LISTENER_PROTOCOL_HTTP3" => Some(Self::Http3),
            "LISTENER_PROTOCOL_TCP" => Some(Self::Tcp),
            "LISTENER_PROTOCOL_UDP" => Some(Self::Udp),
            "LISTENER_PROTOCOL_TLS_PASSTHROUGH" => Some(Self::TlsPassthrough),
            "LISTENER_PROTOCOL_TLS" => Some(Self::Tls),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TlsRouteMode {
    Unspecified = 0,
    Passthrough = 1,
    Terminate = 2,
}
impl TlsRouteMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "TLS_ROUTE_MODE_UNSPECIFIED",
            Self::Passthrough => "TLS_ROUTE_MODE_PASSTHROUGH",
            Self::Terminate => "TLS_ROUTE_MODE_TERMINATE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TLS_ROUTE_MODE_UNSPECIFIED" => Some(Self::Unspecified),
            "TLS_ROUTE_MODE_PASSTHROUGH" => Some(Self::Passthrough),
            "TLS_ROUTE_MODE_TERMINATE" => Some(Self::Terminate),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RouteKind {
    Unspecified = 0,
    Http = 1,
    Grpc = 2,
    Tcp = 3,
    Udp = 4,
    Tls = 5,
}
impl RouteKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ROUTE_KIND_UNSPECIFIED",
            Self::Http => "ROUTE_KIND_HTTP",
            Self::Grpc => "ROUTE_KIND_GRPC",
            Self::Tcp => "ROUTE_KIND_TCP",
            Self::Udp => "ROUTE_KIND_UDP",
            Self::Tls => "ROUTE_KIND_TLS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ROUTE_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "ROUTE_KIND_HTTP" => Some(Self::Http),
            "ROUTE_KIND_GRPC" => Some(Self::Grpc),
            "ROUTE_KIND_TCP" => Some(Self::Tcp),
            "ROUTE_KIND_UDP" => Some(Self::Udp),
            "ROUTE_KIND_TLS" => Some(Self::Tls),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BackendTlsSubjectAltNameType {
    Unspecified = 0,
    Hostname = 1,
    Uri = 2,
}
impl BackendTlsSubjectAltNameType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "BACKEND_TLS_SUBJECT_ALT_NAME_TYPE_UNSPECIFIED",
            Self::Hostname => "BACKEND_TLS_SUBJECT_ALT_NAME_TYPE_HOSTNAME",
            Self::Uri => "BACKEND_TLS_SUBJECT_ALT_NAME_TYPE_URI",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BACKEND_TLS_SUBJECT_ALT_NAME_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "BACKEND_TLS_SUBJECT_ALT_NAME_TYPE_HOSTNAME" => Some(Self::Hostname),
            "BACKEND_TLS_SUBJECT_ALT_NAME_TYPE_URI" => Some(Self::Uri),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SessionPersistenceType {
    Unspecified = 0,
    Cookie = 1,
    Header = 2,
}
impl SessionPersistenceType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SESSION_PERSISTENCE_TYPE_UNSPECIFIED",
            Self::Cookie => "SESSION_PERSISTENCE_TYPE_COOKIE",
            Self::Header => "SESSION_PERSISTENCE_TYPE_HEADER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SESSION_PERSISTENCE_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "SESSION_PERSISTENCE_TYPE_COOKIE" => Some(Self::Cookie),
            "SESSION_PERSISTENCE_TYPE_HEADER" => Some(Self::Header),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CookieLifetimeType {
    Unspecified = 0,
    Session = 1,
    Permanent = 2,
}
impl CookieLifetimeType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "COOKIE_LIFETIME_TYPE_UNSPECIFIED",
            Self::Session => "COOKIE_LIFETIME_TYPE_SESSION",
            Self::Permanent => "COOKIE_LIFETIME_TYPE_PERMANENT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "COOKIE_LIFETIME_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "COOKIE_LIFETIME_TYPE_SESSION" => Some(Self::Session),
            "COOKIE_LIFETIME_TYPE_PERMANENT" => Some(Self::Permanent),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum LoadBalancingPolicyType {
    Unspecified = 0,
    RoundRobin = 1,
    ConsistentHash = 2,
}
impl LoadBalancingPolicyType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "LOAD_BALANCING_POLICY_TYPE_UNSPECIFIED",
            Self::RoundRobin => "LOAD_BALANCING_POLICY_TYPE_ROUND_ROBIN",
            Self::ConsistentHash => "LOAD_BALANCING_POLICY_TYPE_CONSISTENT_HASH",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LOAD_BALANCING_POLICY_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "LOAD_BALANCING_POLICY_TYPE_ROUND_ROBIN" => Some(Self::RoundRobin),
            "LOAD_BALANCING_POLICY_TYPE_CONSISTENT_HASH" => Some(Self::ConsistentHash),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ConsistentHashKeyType {
    Unspecified = 0,
    SourceIp = 1,
    Header = 2,
    Hostname = 3,
}
impl ConsistentHashKeyType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CONSISTENT_HASH_KEY_TYPE_UNSPECIFIED",
            Self::SourceIp => "CONSISTENT_HASH_KEY_TYPE_SOURCE_IP",
            Self::Header => "CONSISTENT_HASH_KEY_TYPE_HEADER",
            Self::Hostname => "CONSISTENT_HASH_KEY_TYPE_HOSTNAME",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CONSISTENT_HASH_KEY_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "CONSISTENT_HASH_KEY_TYPE_SOURCE_IP" => Some(Self::SourceIp),
            "CONSISTENT_HASH_KEY_TYPE_HEADER" => Some(Self::Header),
            "CONSISTENT_HASH_KEY_TYPE_HOSTNAME" => Some(Self::Hostname),
            _ => None,
        }
    }
}
include!("gateway.control.v1.tonic.rs");
// @@protoc_insertion_point(module)