// @generated
// This file is @generated by prost-build.
/// AIServiceConfig configures an AI/LLM provider proxy for a backend cluster.
/// The data plane intercepts requests matching this backend and transforms
/// them into provider-specific API calls (OpenAI, Anthropic, Ollama, etc.).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AiServiceConfig {
    /// AI provider identifier (e.g. "openai", "anthropic", "ollama").
    #[prost(string, tag="1")]
    pub provider: ::prost::alloc::string::String,
    /// API format for request/response transformation (e.g. "openai-chat", "anthropic-messages").
    #[prost(string, tag="2")]
    pub format: ::prost::alloc::string::String,
    /// Default model name to use if not specified in the request.
    #[prost(string, tag="3")]
    pub model: ::prost::alloc::string::String,
    /// Authentication configuration for the AI provider API.
    #[prost(message, optional, tag="4")]
    pub auth: ::core::option::Option<AiServiceAuthConfig>,
    /// Timeout for AI provider API calls.
    #[prost(message, optional, tag="5")]
    pub timeout: ::core::option::Option<::prost_types::Duration>,
    /// Optional endpoint URL override for the AI provider API.
    /// If empty, the data plane uses the provider's default endpoint.
    #[prost(string, tag="6")]
    pub endpoint: ::prost::alloc::string::String,
    /// Maximum number of retry attempts for transient failures.
    #[prost(uint32, tag="7")]
    pub retry_max_retries: u32,
    /// Base backoff duration between retries.
    #[prost(message, optional, tag="8")]
    pub retry_backoff: ::core::option::Option<::prost_types::Duration>,
}
/// AIServiceAuthConfig specifies how the data plane authenticates to an AI provider API.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AiServiceAuthConfig {
    /// Authentication type: "bearer", "api-key", or "basic".
    #[prost(string, tag="1")]
    pub r#type: ::prost::alloc::string::String,
    /// Reference to a SecretMaterial or Kubernetes Secret containing the credential.
    #[prost(string, tag="2")]
    pub secret_ref: ::prost::alloc::string::String,
    /// HTTP header name to inject the credential into (e.g. "Authorization", "x-api-key").
    #[prost(string, tag="3")]
    pub header: ::prost::alloc::string::String,
    /// Key within the Kubernetes Secret to read the credential from.
    #[prost(string, tag="4")]
    pub key: ::prost::alloc::string::String,
}
/// TokenPolicyConfig defines token-based rate limiting for AI model calls.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenPolicyConfig {
    /// Maximum tokens allowed per minute.
    #[prost(uint64, tag="1")]
    pub tokens_per_minute: u64,
    /// Maximum tokens allowed per hour.
    #[prost(uint64, tag="2")]
    pub tokens_per_hour: u64,
    /// Maximum requests allowed per minute.
    #[prost(uint64, tag="3")]
    pub requests_per_minute: u64,
    /// Scope of the rate limit: "global" (across all clients) or "per-user".
    #[prost(string, tag="4")]
    pub scope: ::prost::alloc::string::String,
    /// Burst multiplier: allowed short-term overshoot as a ratio of the rate limit.
    #[prost(double, tag="5")]
    pub burst: f64,
    /// Action when limit is exceeded: "reject" (429), "queue", or "degrade".
    #[prost(string, tag="6")]
    pub on_limit: ::prost::alloc::string::String,
}
/// RoutePolicy provides per-route overrides for timeout, body size,
/// proxy buffering, and connection keepalive settings. When attached
/// to an HttpRoute or GrpcRoute, fields set here override the
/// dataplane global defaults for that route.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RoutePolicy {
    /// Per-route timeout overrides for request, backend, and connection timeouts.
    #[prost(message, optional, tag="1")]
    pub timeout: ::core::option::Option<RoutePolicyTimeout>,
    /// Per-route body and header size limits.
    #[prost(message, optional, tag="2")]
    pub body_limit: ::core::option::Option<RoutePolicyBodyLimit>,
    /// Per-route proxy buffering configuration.
    #[prost(message, optional, tag="3")]
    pub proxy: ::core::option::Option<RoutePolicyProxy>,
    /// Per-route connection keepalive settings for client and upstream connections.
    #[prost(message, optional, tag="4")]
    pub connection: ::core::option::Option<RoutePolicyConnection>,
}
/// RoutePolicyTimeout specifies per-route timeout values that override
/// the dataplane global timeout defaults.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RoutePolicyTimeout {
    /// Maximum duration for the entire request-response cycle (from first byte received to last byte sent).
    #[prost(message, optional, tag="1")]
    pub request: ::core::option::Option<::prost_types::Duration>,
    /// Maximum duration for a single backend request attempt (a single upstream connection).
    #[prost(message, optional, tag="2")]
    pub backend_request: ::core::option::Option<::prost_types::Duration>,
    /// Maximum duration to establish a TCP connection to the backend.
    #[prost(message, optional, tag="3")]
    pub connect: ::core::option::Option<::prost_types::Duration>,
    /// Maximum duration spent finding a viable upstream backend during retries.
    #[prost(message, optional, tag="4")]
    pub next_upstream: ::core::option::Option<::prost_types::Duration>,
}
/// RoutePolicyBodyLimit restricts request body and header sizes on a per-route basis.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RoutePolicyBodyLimit {
    /// Maximum request body size in bytes. Requests exceeding this receive HTTP 413 (Payload Too Large).
    #[prost(uint64, tag="1")]
    pub max_request_body_bytes: u64,
    /// Size of the buffer used to read the request body before writing to a temporary file.
    #[prost(uint64, tag="2")]
    pub request_body_buffer_bytes: u64,
    /// Maximum combined size of all request headers in bytes.
    #[prost(uint64, tag="3")]
    pub max_request_header_bytes: u64,
}
/// RoutePolicyProxy controls HTTP proxy buffering behavior on a per-route basis.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RoutePolicyProxy {
    /// If true, buffer the entire client request body before proxying to the backend.
    #[prost(message, optional, tag="1")]
    pub request_buffering: ::core::option::Option<bool>,
    /// If true, buffer the backend response before sending to the client. If false, stream the response.
    #[prost(message, optional, tag="2")]
    pub response_buffering: ::core::option::Option<bool>,
    /// Size of each response buffer in bytes (used when response_buffering is enabled).
    #[prost(uint64, tag="3")]
    pub buffer_size: u64,
    /// Number of response buffers to allocate (used when response_buffering is enabled).
    #[prost(uint32, tag="4")]
    pub buffer_count: u32,
}
/// RoutePolicyConnection controls keepalive behavior for client-facing and
/// upstream connections on a per-route basis.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RoutePolicyConnection {
    /// Maximum number of requests allowed on a single keepalive client connection.
    #[prost(uint32, tag="1")]
    pub keepalive_requests: u32,
    /// Maximum lifetime of a keepalive client connection.
    #[prost(message, optional, tag="2")]
    pub keepalive_time: ::core::option::Option<::prost_types::Duration>,
    /// Maximum idle time before closing a keepalive client connection.
    #[prost(message, optional, tag="3")]
    pub keepalive_timeout: ::core::option::Option<::prost_types::Duration>,
    /// Maximum number of idle upstream keepalive connections to maintain in the pool.
    #[prost(uint32, tag="4")]
    pub upstream_keepalive_pool_size: u32,
    /// Maximum idle time before closing an upstream keepalive connection.
    #[prost(message, optional, tag="5")]
    pub upstream_keepalive_idle: ::core::option::Option<::prost_types::Duration>,
}
/// WasmPluginConfig describes a WebAssembly plugin to be loaded and executed
/// by the data plane at specified hook points.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WasmPluginConfig {
    /// Plugin name (matches the Kubernetes WasmPlugin resource name).
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    /// Kubernetes namespace of the plugin resource.
    #[prost(string, tag="2")]
    pub namespace: ::prost::alloc::string::String,
    /// Compiled WebAssembly module bytes.
    #[prost(bytes="vec", tag="3")]
    pub wasm_bytes: ::prost::alloc::vec::Vec<u8>,
    /// SHA-256 hash of the Wasm module for integrity verification.
    #[prost(string, tag="4")]
    pub sha256: ::prost::alloc::string::String,
    /// Hook points where this plugin executes (e.g. "http-request-headers",
    /// "http-response-body", "grpc-request").
    #[prost(string, repeated, tag="5")]
    pub hooks: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// JSON configuration passed to the plugin at initialization.
    #[prost(string, tag="6")]
    pub config_json: ::prost::alloc::string::String,
    /// Sandbox constraints for Wasm execution.
    #[prost(message, optional, tag="7")]
    pub sandbox: ::core::option::Option<WasmSandboxConfig>,
    /// Optional reference URL from which the data plane may fetch the module
    /// bytes instead of inlining them in `wasm_bytes`. When both are set,
    /// `wasm_bytes` takes precedence.
    #[prost(string, tag="8")]
    pub source_url: ::prost::alloc::string::String,
}
/// WasmSandboxConfig defines resource limits and security constraints
/// for WebAssembly plugin execution.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WasmSandboxConfig {
    /// Maximum memory the Wasm module can allocate, in bytes.
    #[prost(uint64, tag="1")]
    pub max_memory_bytes: u64,
    /// Maximum execution time per hook invocation, in milliseconds.
    #[prost(uint64, tag="2")]
    pub max_execution_time_ms: u64,
    /// Whether the plugin can make outbound network requests.
    #[prost(bool, tag="3")]
    pub allow_network: bool,
    /// Whether the plugin can access the host file system.
    #[prost(bool, tag="4")]
    pub allow_file_system: bool,
}
/// ConfigSnapshot is a point-in-time, self-consistent configuration bundle
/// pushed from the control plane to the data plane. Every field is replaced
/// wholesale on each push (full-state snapshot, not delta).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConfigSnapshot {
    /// Unique snapshot identifier, typically a UUID or content hash.
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// Timestamp when this snapshot was generated by the control plane.
    #[prost(message, optional, tag="2")]
    pub generated_at: ::core::option::Option<::prost_types::Timestamp>,
    /// All active listeners (port bindings).
    #[prost(message, repeated, tag="3")]
    pub listeners: ::prost::alloc::vec::Vec<Listener>,
    /// All HTTP route rules.
    #[prost(message, repeated, tag="4")]
    pub http_routes: ::prost::alloc::vec::Vec<HttpRoute>,
    /// All gRPC route rules.
    #[prost(message, repeated, tag="5")]
    pub grpc_routes: ::prost::alloc::vec::Vec<GrpcRoute>,
    /// All TCP/UDP/TLS stream route rules.
    #[prost(message, repeated, tag="6")]
    pub stream_routes: ::prost::alloc::vec::Vec<StreamRoute>,
    /// All backend clusters (upstream service discovery results).
    #[prost(message, repeated, tag="7")]
    pub backends: ::prost::alloc::vec::Vec<BackendCluster>,
    /// TLS certificate/key material referenced by listeners and backends.
    #[prost(message, repeated, tag="8")]
    pub secrets: ::prost::alloc::vec::Vec<SecretMaterial>,
    /// Arbitrary extension data, keyed by extension name.
    #[prost(message, optional, tag="9")]
    pub extensions: ::core::option::Option<::prost_types::Struct>,
    /// Features the control plane requires the data plane to support
    /// for this snapshot to be safely applied.
    #[prost(string, repeated, tag="10")]
    pub required_features: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Named compatibility profile (e.g. "v1", "experimental"). The data plane
    /// uses this to enable/disable behavior flags atomically.
    #[prost(string, tag="11")]
    pub compatibility_profile: ::prost::alloc::string::String,
    /// W3C TraceContext traceparent header value. The control plane injects
    /// its current trace context so the data plane can create child spans
    /// linked to the snapshot generation trace.
    #[prost(string, tag="20")]
    pub traceparent: ::prost::alloc::string::String,
}
/// Listener describes a port binding on the data plane. Each listener
/// has a protocol, optional TLS settings, and references to route rules
/// that determine how traffic is dispatched.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Listener {
    /// Unique name for this listener within the data-plane instance.
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    /// IP address to bind to (e.g. "0.0.0.0" for all interfaces).
    #[prost(string, tag="2")]
    pub address: ::prost::alloc::string::String,
    /// TCP/UDP port to listen on.
    #[prost(uint32, tag="3")]
    pub port: u32,
    /// Transport protocol for this listener.
    #[prost(enumeration="ListenerProtocol", tag="4")]
    pub protocol: i32,
    /// Hostnames this listener accepts (SNI matching for TLS, Host header for HTTP).
    #[prost(string, repeated, tag="5")]
    pub hostnames: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Names of route rules attached to this listener. The data plane
    /// resolves these against the snapshot's route tables.
    #[prost(string, repeated, tag="6")]
    pub attached_routes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// TLS configuration for this listener (required for HTTPS/TLS protocols).
    #[prost(message, optional, tag="7")]
    pub tls: ::core::option::Option<TlsConfig>,
    /// Arbitrary key-value metadata.
    #[prost(map="string, string", tag="8")]
    pub metadata: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    /// Default TLS settings applied to backends reached through this listener.
    /// Overridden by per-route or per-backend TLS config when present.
    #[prost(message, optional, tag="9")]
    pub backend_tls: ::core::option::Option<BackendTlsConfig>,
    /// Additional addresses to bind (for dual-stack or multi-interface setups).
    #[prost(string, repeated, tag="10")]
    pub addresses: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// TlsConfig specifies TLS settings for a listener's frontend (client-facing) side.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TlsConfig {
    /// Whether TLS is enabled on this listener.
    #[prost(bool, tag="1")]
    pub enabled: bool,
    /// If true, forward TLS without termination (passthrough mode).
    #[prost(bool, tag="2")]
    pub passthrough: bool,
    /// References to SecretMaterial entries containing server certificate/key pairs.
    #[prost(string, repeated, tag="3")]
    pub secret_refs: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Server Name Indication hostnames this listener responds to.
    #[prost(string, repeated, tag="4")]
    pub sni_hosts: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Minimum TLS version (e.g. "1.2", "1.3").
    #[prost(string, tag="5")]
    pub min_version: ::prost::alloc::string::String,
    /// Maximum TLS version (e.g. "1.3").
    #[prost(string, tag="6")]
    pub max_version: ::prost::alloc::string::String,
    /// Client certificate validation settings (mTLS).
    #[prost(message, optional, tag="7")]
    pub frontend_validation: ::core::option::Option<FrontendValidation>,
}
/// FrontendValidation controls client certificate verification (mTLS) for a listener.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FrontendValidation {
    /// PEM-encoded CA certificates used to verify client certificates.
    #[prost(string, repeated, tag="1")]
    pub ca_pems: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Validation mode: "strict" (require client cert), "optional" (request but don't require),
    /// or empty (no client cert validation).
    #[prost(string, tag="2")]
    pub mode: ::prost::alloc::string::String,
}
/// BackendTlsConfig specifies the client-side TLS settings for connecting
/// to an upstream backend from a listener.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BackendTlsConfig {
    /// Reference to a SecretMaterial entry containing the client certificate
    /// and key pair for backend mTLS.
    #[prost(string, tag="1")]
    pub client_certificate_ref: ::prost::alloc::string::String,
}
/// BackendTlsValidation controls how the data plane validates the backend's TLS certificate.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BackendTlsValidation {
    /// Expected hostname in the backend's certificate (SNI).
    #[prost(string, tag="1")]
    pub hostname: ::prost::alloc::string::String,
    /// If true, use the system's CA certificate store in addition to ca_pems.
    #[prost(bool, tag="2")]
    pub use_system_ca_certificates: bool,
    /// PEM-encoded CA certificates used to verify the backend's certificate.
    #[prost(string, repeated, tag="3")]
    pub ca_pems: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Subject Alternative Names the backend certificate must match.
    #[prost(message, repeated, tag="4")]
    pub subject_alt_names: ::prost::alloc::vec::Vec<BackendTlsSubjectAltName>,
    /// Minimum acceptable TLS version for the backend connection.
    #[prost(string, tag="5")]
    pub min_version: ::prost::alloc::string::String,
    /// Maximum TLS version for the backend connection.
    #[prost(string, tag="6")]
    pub max_version: ::prost::alloc::string::String,
}
/// BackendTlsSubjectAltName describes a single Subject Alternative Name
/// constraint for backend certificate validation.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BackendTlsSubjectAltName {
    /// Type of SAN entry (hostname or URI).
    #[prost(enumeration="BackendTlsSubjectAltNameType", tag="1")]
    pub r#type: i32,
    /// The SAN value to match against the backend certificate.
    #[prost(string, tag="2")]
    pub value: ::prost::alloc::string::String,
}
/// HttpRoute defines HTTP-level routing rules. It is the xDS representation
/// of a Kubernetes HTTPRoute resource after Gateway API translation.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HttpRoute {
    /// Route name (matches the Kubernetes resource name).
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    /// Kubernetes namespace of the route resource.
    #[prost(string, tag="2")]
    pub namespace: ::prost::alloc::string::String,
    /// Hostnames this route matches (Host header).
    #[prost(string, repeated, tag="3")]
    pub hostnames: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// References to parent Gateway listeners this route attaches to.
    #[prost(message, repeated, tag="4")]
    pub parent_refs: ::prost::alloc::vec::Vec<ParentRef>,
    /// Ordered list of HTTP routing rules. First match wins.
    #[prost(message, repeated, tag="5")]
    pub rules: ::prost::alloc::vec::Vec<HttpRule>,
    /// Kubernetes labels from the route resource.
    #[prost(map="string, string", tag="6")]
    pub labels: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    /// Kubernetes annotations from the route resource.
    #[prost(map="string, string", tag="7")]
    pub annotations: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    /// Per-route policy overrides for timeout, body size, proxy buffering,
    /// and connection keepalive settings.
    #[prost(message, optional, tag="8")]
    pub route_policy: ::core::option::Option<RoutePolicy>,
}
/// HttpRule defines a single HTTP routing rule: match conditions, filters
/// to apply, and backends to forward to.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HttpRule {
    /// Match conditions. ALL matches must be satisfied (AND semantics).
    /// At least one match is required.
    #[prost(message, repeated, tag="1")]
    pub matches: ::prost::alloc::vec::Vec<HttpMatch>,
    /// Filters applied to the request before forwarding (e.g. header modification,
    /// URL rewrite, rate limiting).
    #[prost(message, repeated, tag="2")]
    pub filters: ::prost::alloc::vec::Vec<Filter>,
    /// Backends to forward matching requests to. Multiple backends imply
    /// weighted load balancing.
    #[prost(message, repeated, tag="3")]
    pub backend_refs: ::prost::alloc::vec::Vec<BackendRef>,
    /// Request and backend timeout settings for this rule.
    #[prost(message, optional, tag="4")]
    pub timeouts: ::core::option::Option<HttpRouteTimeouts>,
    /// Retry policy for failed requests on this rule.
    #[prost(message, optional, tag="5")]
    pub retry: ::core::option::Option<HttpRouteRetry>,
    /// Session persistence configuration (sticky sessions).
    #[prost(message, optional, tag="6")]
    pub session_persistence: ::core::option::Option<SessionPersistence>,
    /// Optional human-readable name for this rule.
    #[prost(string, tag="7")]
    pub name: ::prost::alloc::string::String,
}
/// HttpMatch defines request matching criteria for an HTTP route rule.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HttpMatch {
    /// URL path pattern to match (e.g. "/api/v1/").
    #[prost(string, tag="1")]
    pub path: ::prost::alloc::string::String,
    /// Path match type: "Exact", "PathPrefix", or "RegularExpression".
    #[prost(string, tag="2")]
    pub path_type: ::prost::alloc::string::String,
    /// HTTP method to match (GET, POST, PUT, DELETE, etc.). Empty matches all.
    #[prost(string, tag="3")]
    pub method: ::prost::alloc::string::String,
    /// Header match conditions. All must match (AND semantics).
    #[prost(message, repeated, tag="4")]
    pub headers: ::prost::alloc::vec::Vec<HeaderMatch>,
    /// Query parameter match conditions. All must match (AND semantics).
    #[prost(message, repeated, tag="5")]
    pub query_params: ::prost::alloc::vec::Vec<QueryMatch>,
}
/// HttpRouteTimeouts specifies timeout values for HTTP requests on a route rule.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HttpRouteTimeouts {
    /// Maximum duration for the entire request-response cycle.
    #[prost(message, optional, tag="1")]
    pub request: ::core::option::Option<::prost_types::Duration>,
    /// Maximum duration for a single backend request attempt.
    #[prost(message, optional, tag="2")]
    pub backend_request: ::core::option::Option<::prost_types::Duration>,
}
/// HttpRouteRetry defines the retry policy for failed HTTP requests.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HttpRouteRetry {
    /// HTTP status codes that trigger a retry (e.g. 502, 503, 504).
    #[prost(uint32, repeated, tag="1")]
    pub codes: ::prost::alloc::vec::Vec<u32>,
    /// Maximum number of retry attempts.
    #[prost(uint32, tag="2")]
    pub attempts: u32,
    /// Backoff duration between retry attempts.
    #[prost(message, optional, tag="3")]
    pub backoff: ::core::option::Option<::prost_types::Duration>,
}
/// CookieConfig specifies cookie-based session persistence settings.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CookieConfig {
    /// Cookie lifetime behavior (session or permanent).
    #[prost(enumeration="CookieLifetimeType", tag="1")]
    pub lifetime_type: i32,
}
/// SessionPersistence configures sticky sessions so requests from the same
/// client are routed to the same backend.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SessionPersistence {
    /// Name of the session cookie or header.
    #[prost(string, tag="1")]
    pub session_name: ::prost::alloc::string::String,
    /// Maximum session duration. The session expires after this time regardless
    /// of activity.
    #[prost(message, optional, tag="2")]
    pub absolute_timeout: ::core::option::Option<::prost_types::Duration>,
    /// Session expires after this duration of inactivity.
    #[prost(message, optional, tag="3")]
    pub idle_timeout: ::core::option::Option<::prost_types::Duration>,
    /// Persistence mechanism (cookie or header).
    #[prost(enumeration="SessionPersistenceType", tag="4")]
    pub r#type: i32,
    /// Cookie-specific settings (only relevant when type is COOKIE).
    #[prost(message, optional, tag="5")]
    pub cookie: ::core::option::Option<CookieConfig>,
}
/// ConsistentHashPolicy configures consistent-hash load balancing behavior.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConsistentHashPolicy {
    /// The hash key type (source IP, header, or hostname).
    #[prost(enumeration="ConsistentHashKeyType", tag="1")]
    pub key_type: i32,
    /// Header name to hash on (required when key_type is HEADER).
    #[prost(string, tag="2")]
    pub header_name: ::prost::alloc::string::String,
}
/// LoadBalancingPolicy configures load balancing for a backend cluster.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoadBalancingPolicy {
    /// Load balancing algorithm to use.
    #[prost(enumeration="LoadBalancingPolicyType", tag="1")]
    pub r#type: i32,
    /// Consistent-hash settings (required when type is CONSISTENT_HASH).
    #[prost(message, optional, tag="2")]
    pub consistent_hash: ::core::option::Option<ConsistentHashPolicy>,
}
/// GrpcRoute defines gRPC-level routing rules. It is the xDS representation
/// of a Kubernetes GRPCRoute resource.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GrpcRoute {
    /// Route name (matches the Kubernetes resource name).
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    /// Kubernetes namespace of the route resource.
    #[prost(string, tag="2")]
    pub namespace: ::prost::alloc::string::String,
    /// Hostnames this route matches (Host header or :authority).
    #[prost(string, repeated, tag="3")]
    pub hostnames: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// References to parent Gateway listeners this route attaches to.
    #[prost(message, repeated, tag="4")]
    pub parent_refs: ::prost::alloc::vec::Vec<ParentRef>,
    /// Ordered list of gRPC routing rules. First match wins.
    #[prost(message, repeated, tag="5")]
    pub rules: ::prost::alloc::vec::Vec<GrpcRule>,
    /// Kubernetes labels from the route resource.
    #[prost(map="string, string", tag="6")]
    pub labels: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    /// Kubernetes annotations from the route resource.
    #[prost(map="string, string", tag="7")]
    pub annotations: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    /// Per-route policy overrides for timeout, body size, proxy buffering,
    /// and connection keepalive settings.
    #[prost(message, optional, tag="8")]
    pub route_policy: ::core::option::Option<RoutePolicy>,
}
/// GrpcRule defines a single gRPC routing rule: service/method matching,
/// filters, and backend forwarding.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GrpcRule {
    /// Match conditions. ALL matches must be satisfied (AND semantics).
    #[prost(message, repeated, tag="1")]
    pub matches: ::prost::alloc::vec::Vec<GrpcMatch>,
    /// Filters applied to the gRPC call before forwarding.
    #[prost(message, repeated, tag="2")]
    pub filters: ::prost::alloc::vec::Vec<Filter>,
    /// Backends to forward matching requests to.
    #[prost(message, repeated, tag="3")]
    pub backend_refs: ::prost::alloc::vec::Vec<BackendRef>,
    /// Session persistence configuration for sticky gRPC sessions.
    #[prost(message, optional, tag="4")]
    pub session_persistence: ::core::option::Option<SessionPersistence>,
    /// Optional human-readable name for this rule.
    #[prost(string, tag="5")]
    pub name: ::prost::alloc::string::String,
}
/// GrpcMatch defines request matching criteria for a gRPC route rule.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GrpcMatch {
    /// Fully qualified gRPC service name (e.g. "helloworld.Greeter").
    #[prost(string, tag="1")]
    pub service: ::prost::alloc::string::String,
    /// gRPC method name (e.g. "SayHello"). Empty matches all methods of the service.
    #[prost(string, tag="2")]
    pub method: ::prost::alloc::string::String,
    /// Header match conditions (metadata headers). All must match (AND semantics).
    #[prost(message, repeated, tag="3")]
    pub headers: ::prost::alloc::vec::Vec<HeaderMatch>,
    /// Match type: "Exact" or "RegularExpression".
    #[prost(string, tag="4")]
    pub match_type: ::prost::alloc::string::String,
}
/// StreamRoute defines TCP/UDP/TLS stream-level routing rules. It is the
/// xDS representation of a Kubernetes TLSRoute/TCPRoute/UDPRoute resource.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamRoute {
    /// Route name (matches the Kubernetes resource name).
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    /// Kubernetes namespace of the route resource.
    #[prost(string, tag="2")]
    pub namespace: ::prost::alloc::string::String,
    /// Transport protocol kind for this route.
    #[prost(enumeration="RouteKind", tag="3")]
    pub kind: i32,
    /// References to parent Gateway listeners this route attaches to.
    #[prost(message, repeated, tag="4")]
    pub parent_refs: ::prost::alloc::vec::Vec<ParentRef>,
    /// Ordered list of stream routing rules. First match wins.
    #[prost(message, repeated, tag="5")]
    pub rules: ::prost::alloc::vec::Vec<StreamRule>,
    /// Kubernetes labels from the route resource.
    #[prost(map="string, string", tag="6")]
    pub labels: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    /// Kubernetes annotations from the route resource.
    #[prost(map="string, string", tag="7")]
    pub annotations: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
/// StreamRule defines a single TCP/UDP/TLS stream routing rule.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamRule {
    /// Match conditions. ALL matches must be satisfied (AND semantics).
    #[prost(message, repeated, tag="1")]
    pub matches: ::prost::alloc::vec::Vec<StreamMatch>,
    /// Backends to forward matching connections to.
    #[prost(message, repeated, tag="2")]
    pub backend_refs: ::prost::alloc::vec::Vec<BackendRef>,
    /// Optional human-readable name for this rule.
    #[prost(string, tag="3")]
    pub name: ::prost::alloc::string::String,
}
/// StreamMatch defines connection matching criteria for a stream route rule.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StreamMatch {
    /// Destination port to match on.
    #[prost(uint32, tag="1")]
    pub port: u32,
    /// SNI hostname to match (TLS passthrough routes only).
    #[prost(string, tag="2")]
    pub sni_hostname: ::prost::alloc::string::String,
    /// TLS handling mode for this match.
    #[prost(enumeration="TlsRouteMode", tag="3")]
    pub mode: i32,
}
/// ParentRef identifies a parent Gateway resource that a route attaches to.
/// Mirrors the Kubernetes Gateway API ParentReference.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ParentRef {
    /// API group of the parent resource (e.g. "gateway.networking.k8s.io").
    #[prost(string, tag="1")]
    pub group: ::prost::alloc::string::String,
    /// Kind of the parent resource (e.g. "Gateway").
    #[prost(string, tag="2")]
    pub kind: ::prost::alloc::string::String,
    /// Namespace of the parent resource.
    #[prost(string, tag="3")]
    pub namespace: ::prost::alloc::string::String,
    /// Name of the parent resource.
    #[prost(string, tag="4")]
    pub name: ::prost::alloc::string::String,
    /// Section name within the parent (e.g. listener name in a Gateway).
    #[prost(string, tag="5")]
    pub section_name: ::prost::alloc::string::String,
    /// Port of the parent listener.
    #[prost(uint32, tag="6")]
    pub port: u32,
}
/// BackendRef references a backend service to forward traffic to.
/// Mirrors the Kubernetes Gateway API BackendRef with extensions.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BackendRef {
    /// API group of the backend resource (e.g. "" for core Service).
    #[prost(string, tag="1")]
    pub group: ::prost::alloc::string::String,
    /// Kind of the backend resource (e.g. "Service").
    #[prost(string, tag="2")]
    pub kind: ::prost::alloc::string::String,
    /// Namespace of the backend resource.
    #[prost(string, tag="3")]
    pub namespace: ::prost::alloc::string::String,
    /// Name of the backend resource.
    #[prost(string, tag="4")]
    pub name: ::prost::alloc::string::String,
    /// Port on the backend to forward to.
    #[prost(uint32, tag="5")]
    pub port: u32,
    /// Traffic weight for this backend (0-100). Used for weighted load balancing
    /// when multiple backends are specified.
    #[prost(uint32, tag="6")]
    pub weight: u32,
    /// Arbitrary key-value metadata attached to this backend reference.
    #[prost(map="string, string", tag="7")]
    pub metadata: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    /// Per-backend filters applied only to traffic forwarded to this backend.
    #[prost(message, repeated, tag="8")]
    pub filters: ::prost::alloc::vec::Vec<Filter>,
}
/// BackendCluster represents a discovered upstream service with its endpoints,
/// timeouts, TLS settings, and optional AI/Token/Wasm plugin configuration.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BackendCluster {
    /// Cluster name (typically the Kubernetes Service name).
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    /// Kubernetes namespace of the backend service.
    #[prost(string, tag="2")]
    pub namespace: ::prost::alloc::string::String,
    /// Protocol for backend connections (HTTP, gRPC, TCP, etc.).
    #[prost(string, tag="3")]
    pub protocol: ::prost::alloc::string::String,
    /// Discovered backend endpoints (IP:port pairs).
    #[prost(message, repeated, tag="4")]
    pub endpoints: ::prost::alloc::vec::Vec<BackendEndpoint>,
    /// Connection establishment timeout for new backend connections.
    #[prost(message, optional, tag="5")]
    pub connect_timeout: ::core::option::Option<::prost_types::Duration>,
    /// Total request timeout for backend requests.
    #[prost(message, optional, tag="6")]
    pub request_timeout: ::core::option::Option<::prost_types::Duration>,
    /// Arbitrary key-value metadata.
    #[prost(map="string, string", tag="7")]
    pub metadata: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    /// TLS validation settings for connections to this backend.
    #[prost(message, optional, tag="8")]
    pub tls_validation: ::core::option::Option<BackendTlsValidation>,
    /// Session persistence configuration override for this backend.
    #[prost(message, optional, tag="9")]
    pub session_persistence: ::core::option::Option<SessionPersistence>,
    /// Load balancing policy for this backend cluster.
    #[prost(message, optional, tag="10")]
    pub load_balancing: ::core::option::Option<LoadBalancingPolicy>,
    /// AI service configuration (LLM provider proxy settings).
    #[prost(message, optional, tag="11")]
    pub ai_service: ::core::option::Option<AiServiceConfig>,
    /// Token rate limiting policy for AI model calls.
    #[prost(message, optional, tag="12")]
    pub token_policy: ::core::option::Option<TokenPolicyConfig>,
    /// WebAssembly plugin configuration attached to this backend.
    #[prost(message, optional, tag="13")]
    pub wasm_plugin: ::core::option::Option<WasmPluginConfig>,
    /// Per-backend circuit breaker configuration.
    #[prost(message, optional, tag="14")]
    pub circuit_breaker: ::core::option::Option<CircuitBreakerConfig>,
}
/// CircuitBreakerConfig defines per-backend circuit breaker thresholds.
/// When not set, the data plane uses its default circuit breaker settings.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CircuitBreakerConfig {
    /// Maximum number of concurrent inflight requests allowed to this backend.
    /// Requests beyond this limit are rejected immediately with a 503.
    /// Set to 0 to disable circuit breaking for this backend.
    #[prost(uint32, tag="1")]
    pub max_inflight_requests: u32,
}
/// BackendEndpoint represents a single backend instance discovered by the control plane.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BackendEndpoint {
    /// IP address of the backend instance.
    #[prost(string, tag="1")]
    pub address: ::prost::alloc::string::String,
    /// Port the backend listens on.
    #[prost(uint32, tag="2")]
    pub port: u32,
    /// Whether the endpoint is currently healthy based on health checks.
    #[prost(bool, tag="3")]
    pub healthy: bool,
    /// Availability zone or topology zone of the endpoint (for zone-aware routing).
    #[prost(string, tag="4")]
    pub zone: ::prost::alloc::string::String,
}
/// HeaderMatch defines a request header matching condition.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HeaderMatch {
    /// Header name to match (case-insensitive for HTTP/1.1).
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    /// Expected header value.
    #[prost(string, tag="2")]
    pub value: ::prost::alloc::string::String,
    /// Match type: "Exact", "Prefix", "Suffix", "RegularExpression", or "Present".
    #[prost(string, tag="3")]
    pub match_type: ::prost::alloc::string::String,
}
/// QueryMatch defines a URL query parameter matching condition.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryMatch {
    /// Query parameter name to match.
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    /// Expected query parameter value.
    #[prost(string, tag="2")]
    pub value: ::prost::alloc::string::String,
    /// Match type: "Exact" or "RegularExpression".
    #[prost(string, tag="3")]
    pub match_type: ::prost::alloc::string::String,
}
/// Filter represents a request/response processing filter applied to a route or backend.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Filter {
    /// Filter type identifier (e.g. "RequestHeaderModifier", "ResponseHeaderModifier",
    /// "URLRewrite", "RequestRedirect", "ExtensionRef").
    #[prost(string, tag="1")]
    pub r#type: ::prost::alloc::string::String,
    /// Filter-specific configuration. Shape depends on the filter type.
    #[prost(message, optional, tag="2")]
    pub config: ::core::option::Option<::prost_types::Struct>,
}
/// SecretMaterial carries TLS certificate and key data referenced by listeners
/// and backend connections.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SecretMaterial {
    /// Kubernetes namespace of the Secret resource.
    #[prost(string, tag="1")]
    pub namespace: ::prost::alloc::string::String,
    /// Kubernetes name of the Secret resource.
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    /// PEM-encoded certificate data.
    #[prost(string, tag="3")]
    pub cert_pem: ::prost::alloc::string::String,
    /// PEM-encoded private key data.
    #[prost(string, tag="4")]
    pub key_pem: ::prost::alloc::string::String,
}
/// ListenerProtocol enumerates the transport-layer protocols a listener can serve.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ListenerProtocol {
    /// Default unspecified value. Should not be used.
    ListenerUnspecified = 0,
    /// Plain HTTP/1.1 and HTTP/2 (H2C).
    ListenerHttp = 1,
    /// HTTPS with TLS termination at the data plane.
    ListenerHttps = 2,
    /// gRPC (HTTP/2 with application/grpc content type).
    ListenerGrpc = 3,
    /// HTTP/3 over QUIC.
    ListenerHttp3 = 4,
    /// Raw TCP proxying.
    ListenerTcp = 5,
    /// Raw UDP proxying.
    ListenerUdp = 6,
    /// TLS passthrough — the data plane forwards the TLS handshake
    /// without termination, routing based on SNI.
    ListenerTlsPassthrough = 7,
    /// Generic TLS with termination at the data plane.
    ListenerTls = 8,
}
impl ListenerProtocol {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::ListenerUnspecified => "LISTENER_UNSPECIFIED",
            Self::ListenerHttp => "LISTENER_HTTP",
            Self::ListenerHttps => "LISTENER_HTTPS",
            Self::ListenerGrpc => "LISTENER_GRPC",
            Self::ListenerHttp3 => "LISTENER_HTTP3",
            Self::ListenerTcp => "LISTENER_TCP",
            Self::ListenerUdp => "LISTENER_UDP",
            Self::ListenerTlsPassthrough => "LISTENER_TLS_PASSTHROUGH",
            Self::ListenerTls => "LISTENER_TLS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LISTENER_UNSPECIFIED" => Some(Self::ListenerUnspecified),
            "LISTENER_HTTP" => Some(Self::ListenerHttp),
            "LISTENER_HTTPS" => Some(Self::ListenerHttps),
            "LISTENER_GRPC" => Some(Self::ListenerGrpc),
            "LISTENER_HTTP3" => Some(Self::ListenerHttp3),
            "LISTENER_TCP" => Some(Self::ListenerTcp),
            "LISTENER_UDP" => Some(Self::ListenerUdp),
            "LISTENER_TLS_PASSTHROUGH" => Some(Self::ListenerTlsPassthrough),
            "LISTENER_TLS" => Some(Self::ListenerTls),
            _ => None,
        }
    }
}
/// TlsRouteMode controls how a stream (TCP/TLS) listener handles TLS connections.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TlsRouteMode {
    /// Default unspecified value. Should not be used.
    TlsRouteUnspecified = 0,
    /// Forward the raw TLS stream to the backend without termination.
    TlsRoutePassthrough = 1,
    /// Terminate TLS at the data plane and forward plain text to the backend.
    TlsRouteTerminate = 2,
}
impl TlsRouteMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::TlsRouteUnspecified => "TLS_ROUTE_UNSPECIFIED",
            Self::TlsRoutePassthrough => "TLS_ROUTE_PASSTHROUGH",
            Self::TlsRouteTerminate => "TLS_ROUTE_TERMINATE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TLS_ROUTE_UNSPECIFIED" => Some(Self::TlsRouteUnspecified),
            "TLS_ROUTE_PASSTHROUGH" => Some(Self::TlsRoutePassthrough),
            "TLS_ROUTE_TERMINATE" => Some(Self::TlsRouteTerminate),
            _ => None,
        }
    }
}
/// RouteKind classifies a stream route by transport protocol.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RouteKind {
    /// Default unspecified value. Should not be used.
    Unspecified = 0,
    /// HTTP route (layer 7, path/host/header matching).
    Http = 1,
    /// gRPC route (layer 7, service/method matching).
    Grpc = 2,
    /// Raw TCP stream route (layer 4, port matching).
    Tcp = 3,
    /// Raw UDP stream route (layer 4, port matching).
    Udp = 4,
    /// TLS stream route (layer 4, SNI matching).
    Tls = 5,
}
impl RouteKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ROUTE_KIND_UNSPECIFIED",
            Self::Http => "ROUTE_KIND_HTTP",
            Self::Grpc => "ROUTE_KIND_GRPC",
            Self::Tcp => "ROUTE_KIND_TCP",
            Self::Udp => "ROUTE_KIND_UDP",
            Self::Tls => "ROUTE_KIND_TLS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ROUTE_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "ROUTE_KIND_HTTP" => Some(Self::Http),
            "ROUTE_KIND_GRPC" => Some(Self::Grpc),
            "ROUTE_KIND_TCP" => Some(Self::Tcp),
            "ROUTE_KIND_UDP" => Some(Self::Udp),
            "ROUTE_KIND_TLS" => Some(Self::Tls),
            _ => None,
        }
    }
}
/// BackendTlsSubjectAltNameType classifies SAN entries in backend certificates.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BackendTlsSubjectAltNameType {
    /// Default unspecified value. Should not be used.
    BackendTlsSanUnspecified = 0,
    /// DNS hostname (e.g. "backend.example.com").
    BackendTlsSanHostname = 1,
    /// URI (e.g. "spiffe://cluster.local/ns/default/sa/backend").
    BackendTlsSanUri = 2,
}
impl BackendTlsSubjectAltNameType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::BackendTlsSanUnspecified => "BACKEND_TLS_SAN_UNSPECIFIED",
            Self::BackendTlsSanHostname => "BACKEND_TLS_SAN_HOSTNAME",
            Self::BackendTlsSanUri => "BACKEND_TLS_SAN_URI",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BACKEND_TLS_SAN_UNSPECIFIED" => Some(Self::BackendTlsSanUnspecified),
            "BACKEND_TLS_SAN_HOSTNAME" => Some(Self::BackendTlsSanHostname),
            "BACKEND_TLS_SAN_URI" => Some(Self::BackendTlsSanUri),
            _ => None,
        }
    }
}
/// SessionPersistenceType selects the mechanism for sticky sessions.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SessionPersistenceType {
    /// Default unspecified value. Should not be used.
    SessionPersistenceUnspecified = 0,
    /// Use a cookie to track session affinity.
    SessionPersistenceCookie = 1,
    /// Use a request header to track session affinity.
    SessionPersistenceHeader = 2,
}
impl SessionPersistenceType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::SessionPersistenceUnspecified => "SESSION_PERSISTENCE_UNSPECIFIED",
            Self::SessionPersistenceCookie => "SESSION_PERSISTENCE_COOKIE",
            Self::SessionPersistenceHeader => "SESSION_PERSISTENCE_HEADER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SESSION_PERSISTENCE_UNSPECIFIED" => Some(Self::SessionPersistenceUnspecified),
            "SESSION_PERSISTENCE_COOKIE" => Some(Self::SessionPersistenceCookie),
            "SESSION_PERSISTENCE_HEADER" => Some(Self::SessionPersistenceHeader),
            _ => None,
        }
    }
}
/// CookieLifetimeType controls the lifetime of session persistence cookies.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CookieLifetimeType {
    /// Default unspecified value. Should not be used.
    CookieLifetimeUnspecified = 0,
    /// Cookie expires when the browser session ends.
    CookieLifetimeSession = 1,
    /// Cookie persists across browser sessions (absolute timeout).
    CookieLifetimePermanent = 2,
}
impl CookieLifetimeType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::CookieLifetimeUnspecified => "COOKIE_LIFETIME_UNSPECIFIED",
            Self::CookieLifetimeSession => "COOKIE_LIFETIME_SESSION",
            Self::CookieLifetimePermanent => "COOKIE_LIFETIME_PERMANENT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "COOKIE_LIFETIME_UNSPECIFIED" => Some(Self::CookieLifetimeUnspecified),
            "COOKIE_LIFETIME_SESSION" => Some(Self::CookieLifetimeSession),
            "COOKIE_LIFETIME_PERMANENT" => Some(Self::CookieLifetimePermanent),
            _ => None,
        }
    }
}
/// LoadBalancingPolicyType selects the load balancing algorithm for a backend cluster.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum LoadBalancingPolicyType {
    /// Default unspecified value. Should not be used.
    LoadBalancingUnspecified = 0,
    /// Distribute requests evenly across all healthy backends.
    LoadBalancingRoundRobin = 1,
    /// Hash requests to consistently map the same client to the same backend.
    LoadBalancingConsistentHash = 2,
}
impl LoadBalancingPolicyType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::LoadBalancingUnspecified => "LOAD_BALANCING_UNSPECIFIED",
            Self::LoadBalancingRoundRobin => "LOAD_BALANCING_ROUND_ROBIN",
            Self::LoadBalancingConsistentHash => "LOAD_BALANCING_CONSISTENT_HASH",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LOAD_BALANCING_UNSPECIFIED" => Some(Self::LoadBalancingUnspecified),
            "LOAD_BALANCING_ROUND_ROBIN" => Some(Self::LoadBalancingRoundRobin),
            "LOAD_BALANCING_CONSISTENT_HASH" => Some(Self::LoadBalancingConsistentHash),
            _ => None,
        }
    }
}
/// ConsistentHashKeyType selects the key used for consistent-hash load balancing.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ConsistentHashKeyType {
    /// Default unspecified value. Should not be used.
    ConsistentHashUnspecified = 0,
    /// Hash based on the client's source IP address.
    ConsistentHashSourceIp = 1,
    /// Hash based on a specific request header value.
    ConsistentHashHeader = 2,
    /// Hash based on the request's Host header.
    ConsistentHashHostname = 3,
}
impl ConsistentHashKeyType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::ConsistentHashUnspecified => "CONSISTENT_HASH_UNSPECIFIED",
            Self::ConsistentHashSourceIp => "CONSISTENT_HASH_SOURCE_IP",
            Self::ConsistentHashHeader => "CONSISTENT_HASH_HEADER",
            Self::ConsistentHashHostname => "CONSISTENT_HASH_HOSTNAME",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CONSISTENT_HASH_UNSPECIFIED" => Some(Self::ConsistentHashUnspecified),
            "CONSISTENT_HASH_SOURCE_IP" => Some(Self::ConsistentHashSourceIp),
            "CONSISTENT_HASH_HEADER" => Some(Self::ConsistentHashHeader),
            "CONSISTENT_HASH_HOSTNAME" => Some(Self::ConsistentHashHostname),
            _ => None,
        }
    }
}
/// DeltaDiscoveryRequest carries per-resource subscription updates,
/// ACK/NACK responses, and resource version tracking for incremental
/// configuration delivery.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeltaDiscoveryRequest {
    /// Unique identifier for this data-plane instance (e.g. pod name).
    #[prost(string, tag="1")]
    pub node_id: ::prost::alloc::string::String,
    /// Kubernetes cluster name the data plane belongs to.
    #[prost(string, tag="2")]
    pub cluster: ::prost::alloc::string::String,
    /// --- Subscription management ---
    /// Resource type URLs to subscribe to (e.g. "type.googleapis.com/gateway.control.v1.Listener").
    /// Sent on initial connection and when the data plane wants to add subscriptions.
    #[prost(string, repeated, tag="3")]
    pub resource_names_subscribe: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Resource type URLs to unsubscribe from.
    #[prost(string, repeated, tag="4")]
    pub resource_names_unsubscribe: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// --- Resource version tracking ---
    /// Map from resource type URL to per-resource version strings.
    /// Sent on initial connection to seed the control plane's per-client state.
    /// Format: key=type_url, value=map<resource_name, version> serialized as JSON.
    #[prost(map="string, string", tag="5")]
    pub initial_resource_versions: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    /// --- ACK/NACK ---
    /// Nonce from the last received DeltaDiscoveryResponse, echoed back for correlation.
    #[prost(string, tag="6")]
    pub response_nonce: ::prost::alloc::string::String,
    /// Type URL of the resource being acknowledged/rejected.
    #[prost(string, tag="7")]
    pub type_url: ::prost::alloc::string::String,
    /// Whether the last delta response was accepted or rejected.
    #[prost(enumeration="DiscoveryResultStatus", tag="8")]
    pub result_status: i32,
    /// Human-readable error detail when result_status is NACK.
    #[prost(string, tag="9")]
    pub error_detail: ::prost::alloc::string::String,
    /// --- Capability negotiation ---
    /// Features this data plane supports (e.g. "incremental-config", "wildcard-subscription").
    #[prost(string, repeated, tag="10")]
    pub supported_features: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// DeltaDiscoveryResponse carries a batch of resource changes for a
/// single resource type. The control plane sends one response per
/// resource type that has changes.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeltaDiscoveryResponse {
    /// System version identifier (monotonically increasing).
    #[prost(string, tag="1")]
    pub system_version_info: ::prost::alloc::string::String,
    /// Unique nonce for this response. The data plane echoes it back in
    /// the next DeltaDiscoveryRequest for ACK/NACK correlation.
    #[prost(string, tag="2")]
    pub nonce: ::prost::alloc::string::String,
    /// --- Resource payload ---
    /// Type URL for the resources in this response.
    #[prost(string, tag="3")]
    pub type_url: ::prost::alloc::string::String,
    /// Resources that were added or changed since the last response.
    /// Each Resource wraps the actual proto payload in google.protobuf.Any
    /// and carries its own name and version.
    #[prost(message, repeated, tag="4")]
    pub resources: ::prost::alloc::vec::Vec<Resource>,
    /// Names of resources that were removed (no longer present in the
    /// control plane's state). The data plane should delete these from
    /// its local cache.
    #[prost(string, repeated, tag="5")]
    pub removed_resources: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// --- Wildcard (non-incremental) ---
    /// If true, this response replaces ALL resources of this type_url,
    /// not just the changed ones. Equivalent to a SotW push for this type.
    #[prost(bool, tag="6")]
    pub non_incremental: bool,
}
/// Resource wraps a single xDS resource with its name, version, and
/// serialized payload. The payload is an opaque google.protobuf.Any
/// that the data plane unmarshals based on type_url.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Resource {
    /// Unique name of this resource within its type (e.g. listener name, route name).
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    /// Version of this resource. Changes when the resource content changes.
    /// Used by the control plane to compute diffs per-client.
    #[prost(string, tag="2")]
    pub version: ::prost::alloc::string::String,
    /// The actual resource payload, serialized as google.protobuf.Any.
    /// The type URL in the Any matches the type_url in DeltaDiscoveryResponse.
    #[prost(message, optional, tag="3")]
    pub resource: ::core::option::Option<::prost_types::Any>,
    /// Optional alias for this resource (used for LDS→RDS indirection, etc.).
    #[prost(string, tag="4")]
    pub alias: ::prost::alloc::string::String,
    /// Time-to-live hint. If set, the data plane should re-request this
    /// resource before the TTL expires. 0 means indefinite.
    #[prost(message, optional, tag="5")]
    pub ttl: ::core::option::Option<::prost_types::Duration>,
}
/// DiscoveryRequest is sent by the data plane when opening or updating
/// a configuration stream, and after receiving a DiscoveryResponse to
/// acknowledge or reject the snapshot.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DiscoveryRequest {
    /// Unique identifier for this data-plane instance (e.g. pod name).
    #[prost(string, tag="1")]
    pub node_id: ::prost::alloc::string::String,
    /// Kubernetes cluster name the data plane belongs to.
    #[prost(string, tag="2")]
    pub cluster: ::prost::alloc::string::String,
    /// Last accepted configuration version, used for incremental sync.
    #[prost(string, tag="3")]
    pub version: ::prost::alloc::string::String,
    /// Nonce from the last received DiscoveryResponse, echoed back for ACK/NACK correlation.
    #[prost(string, tag="4")]
    pub nonce: ::prost::alloc::string::String,
    /// Resource type URLs this data-plane instance subscribes to.
    #[prost(string, repeated, tag="5")]
    pub subscriptions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Whether the last snapshot was accepted or rejected.
    #[prost(enumeration="DiscoveryResultStatus", tag="6")]
    pub result_status: i32,
    /// Human-readable error detail when result_status is NACK.
    #[prost(string, tag="7")]
    pub error_detail: ::prost::alloc::string::String,
    /// List of optional features this data plane supports, used for
    /// capability negotiation (e.g. "config-sync", "access-log-v2").
    #[prost(string, repeated, tag="8")]
    pub supported_features: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// DiscoveryResponse is sent by the control plane in reply to a
/// DiscoveryRequest, carrying a full ConfigSnapshot.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DiscoveryResponse {
    /// Configuration version identifier. Incremented on every snapshot change.
    #[prost(string, tag="1")]
    pub version: ::prost::alloc::string::String,
    /// Unique nonce for this response. The data plane echoes it back in the
    /// next DiscoveryRequest for ACK/NACK correlation.
    #[prost(string, tag="2")]
    pub nonce: ::prost::alloc::string::String,
    /// The complete configuration snapshot.
    #[prost(message, optional, tag="3")]
    pub snapshot: ::core::option::Option<ConfigSnapshot>,
}
/// StatusReport is sent periodically by the data plane to inform the
/// control plane of its current health and readiness.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StatusReport {
    /// Unique identifier for this data-plane instance.
    #[prost(string, tag="1")]
    pub node_id: ::prost::alloc::string::String,
    /// Currently applied configuration version.
    #[prost(string, tag="2")]
    pub version: ::prost::alloc::string::String,
    /// Whether the data plane is ready to serve traffic.
    #[prost(bool, tag="3")]
    pub ready: bool,
    /// Human-readable status message (e.g. "healthy", "degraded: no backends").
    #[prost(string, tag="4")]
    pub message: ::prost::alloc::string::String,
    /// Timestamp when this status was observed.
    #[prost(message, optional, tag="5")]
    pub observed_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// StatusAck is the control plane's acknowledgement of a StatusReport.
/// It confirms receipt and optionally carries back instructions to the
/// data plane (future: e.g. "reload", "drain", "shutdown").
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StatusAck {
    /// Whether the status report was received and processed successfully.
    #[prost(bool, tag="1")]
    pub accepted: bool,
}
/// DiscoveryResultStatus encodes the data plane's response to a received
/// ConfigSnapshot: ACK means accepted and applied, NACK means rejected.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DiscoveryResultStatus {
    /// Default unspecified value. Should not be used.
    DiscoveryUnspecified = 0,
    /// The ConfigSnapshot was accepted and successfully applied.
    DiscoveryAck = 1,
    /// The ConfigSnapshot was rejected. See error_detail for the reason.
    DiscoveryNack = 2,
}
impl DiscoveryResultStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::DiscoveryUnspecified => "DISCOVERY_UNSPECIFIED",
            Self::DiscoveryAck => "DISCOVERY_ACK",
            Self::DiscoveryNack => "DISCOVERY_NACK",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DISCOVERY_UNSPECIFIED" => Some(Self::DiscoveryUnspecified),
            "DISCOVERY_ACK" => Some(Self::DiscoveryAck),
            "DISCOVERY_NACK" => Some(Self::DiscoveryNack),
            _ => None,
        }
    }
}
include!("gateway.control.v1.tonic.rs");
// @@protoc_insertion_point(module)