[package]
name = "ntgw-xds"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
http.workspace = true
thiserror.workspace = true
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
prost.workspace = true
prost-types.workspace = true
rustls.workspace = true
serde.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tonic.workspace = true
tracing.workspace = true
ntgw-ir.workspace = true
ntgw-observability.workspace = true
ntgw-proto.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true
