[package]
name = "aeg-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
allocator-mimalloc = ["aeg-allocator/allocator-mimalloc"]
allocator-jemalloc = ["aeg-allocator/allocator-jemalloc"]

[dependencies]
anyhow.workspace = true
axum.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
subtle.workspace = true
tokio.workspace = true
tracing.workspace = true
aeg-allocator.workspace = true
aeg-config.workspace = true
aeg-http.workspace = true
aeg-ir.workspace = true
aeg-observability.workspace = true
aeg-shared-tls.workspace = true
aeg-stream.workspace = true
aeg-xds.workspace = true

[dev-dependencies]
tower.workspace = true
