[package]
name = "aeg-stream"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
tokio.workspace = true
tracing.workspace = true
aeg-ir.workspace = true
dashmap.workspace = true
aeg-observability.workspace = true

[dev-dependencies]
proptest.workspace = true
