[package]
name = "ntgw-ir"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arc-swap.workspace = true
form_urlencoded.workspace = true
parking_lot.workspace = true
prost-types.workspace = true
regex.workspace = true
serde.workspace = true
tokio.workspace = true
tracing.workspace = true
ntgw-config = { path = "../ntgw-config" }
ntgw-proto.workspace = true

[dev-dependencies]
proptest.workspace = true
