[package]
name = "ntgw-proto"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
prost.workspace = true
prost-types.workspace = true
tonic.workspace = true

[build-dependencies]
protoc-bin-vendored = "3.2.0"
tonic-build.workspace = true
ureq = { version = "2", default-features = false, features = ["tls"] }
