[package]
name = "ntgw-allocator"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
allocator-mimalloc = ["dep:mimalloc"]
allocator-jemalloc = ["dep:tikv-jemallocator"]

[dependencies]
mimalloc = { workspace = true, optional = true }
tikv-jemallocator = { workspace = true, optional = true }
