[package]
name = "aeg-ir"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
form_urlencoded.workspace = true
parking_lot.workspace = true
prost-types.workspace = true
regex.workspace = true
serde.workspace = true
tokio.workspace = true
aeg-proto.workspace = true

[dev-dependencies]
proptest.workspace = true
