[package]
name = "aeg-shared-tls"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
tokio.workspace = true
tracing.workspace = true
pingora.workspace = true
aeg-http.workspace = true
aeg-ir.workspace = true
aeg-observability.workspace = true
aeg-stream.workspace = true
socket2.workspace = true

[dev-dependencies]
proptest.workspace = true
